import { useMemo, useState, type ReactNode } from 'react';
import { Pressable, View, useWindowDimensions } from 'react-native';
import { ChevronDown, FileText, Info, SlidersHorizontal, Sparkles } from 'lucide-react-native';
import { useRouter } from 'expo-router';
import { useTranslation } from 'react-i18next';
import { AppText, Button, Card, Screen, Sheet, useTheme } from '@/design-system';
import { localDateKey } from '@/domain/records';
import { displayDate, recordSummary, recordTitle } from '@/i18n/recordPresentation';
import { useAppStore } from '@/state/useAppStore';

type Range = 7 | 14 | 30;
const daysAgo = (days: number) => { const date = new Date(); date.setHours(12, 0, 0, 0); date.setDate(date.getDate() - days + 1); return localDateKey(date); };

export function InsightsScreen() {
  const theme = useTheme(); const { width } = useWindowDimensions(); const desktop = width > 820; const router = useRouter(); const { t, i18n } = useTranslation(['insights', 'common']);
  const records = useAppStore((state) => state.records); const [range, setRange] = useState<Range>(7); const [expanded, setExpanded] = useState(false); const [relatedOpen, setRelatedOpen] = useState(false);
  const rangeRecords = useMemo(() => records.filter((record) => record.localDate >= daysAgo(range)), [records, range]); const bowel = rangeRecords.filter((record) => record.kind === 'bowel'); const symptoms = rangeRecords.filter((record) => record.kind === 'symptom'); const loggedDays = new Set(rangeRecords.map((record) => record.localDate)).size;
  const stoolCounts = [1, 2, 3, 4, 5].map((type) => bowel.filter((record) => record.details.stoolType === type).length); const maxStool = Math.max(1, ...stoolCounts); const bloating = symptoms.filter((record) => record.details.symptoms.some((entry) => entry.code === 'bloating')).length; const pain = symptoms.filter((record) => record.details.symptoms.some((entry) => entry.code === 'pain')).length; const related = rangeRecords.filter((record) => record.kind === 'food' || (record.kind === 'symptom' && record.details.symptoms.some((entry) => entry.code === 'bloating'))).slice(0, 8); const active = Math.min(100, Math.round((loggedDays / range) * 100));
  return <Screen topbar>
    <View style={{ marginTop: theme.spacing.md, gap: theme.spacing.md }}>
      <View style={{ flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' }}><View style={{ gap: theme.spacing.sm }}><AppText variant="eyebrow" tone="secondary">{t('subtitle').toUpperCase()}</AppText><AppText variant="webPageTitle" accessibilityRole="header">{t('title')}</AppText></View><Pressable accessibilityRole="button" accessibilityLabel={t('range')} onPress={() => setRange((value) => value === 7 ? 30 : 7)} style={{ minHeight: theme.controls.minimumTouchTarget - theme.spacing.sm, paddingHorizontal: theme.spacing.md, borderRadius: theme.radius.md, borderWidth: theme.controls.borderWidth, borderColor: theme.colors.border.default, backgroundColor: theme.colors.surface.card, flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm }}><SlidersHorizontal size={theme.controls.smallIcon} color={theme.colors.text.primary} /><AppText variant="label">{t('range', { defaultValue: 'range' })}</AppText></Pressable></View>
      <View style={{ flexDirection: 'row', gap: theme.spacing.xs, marginTop: theme.spacing.lg, marginBottom: theme.spacing.sm }}>{([7, 14, 30] as Range[]).map((value) => <Pressable key={value} accessibilityRole="tab" accessibilityState={{ selected: range === value }} onPress={() => setRange(value)} style={{ paddingVertical: theme.spacing.sm + theme.spacing.xs / 4, paddingHorizontal: theme.spacing.md, borderRadius: theme.radius.sm, backgroundColor: range === value ? theme.colors.feedback.success.bg : 'transparent' }}><AppText variant="label" style={{ fontSize: theme.typography.caption.fontSize - theme.spacing.xs, color: range === value ? theme.colors.feedback.success.fg : theme.colors.text.secondary }}>{value} {t('days')}</AppText></Pressable>)}</View>
      <View style={{ flexDirection: desktop ? 'row' : 'column', gap: theme.spacing.md }}>
        <ChartCard title={t('stoolTitle')} eyebrow={t('stoolEyebrow', { defaultValue: 'BOWEL TYPES' })} period={t('period', { range })} desktop={desktop}><View style={{ gap: theme.controls.insightsChartGap, marginVertical: theme.spacing.md }}>{stoolCounts.map((count, index) => <View key={index} style={{ flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm }}><AppText variant="caption" style={{ width: theme.controls.minimumTouchTarget, fontSize: theme.typography.eyebrow.fontSize }}>{t('type', { type: index + 1 })}</AppText><View style={{ flex: 1, height: theme.spacing.sm, borderRadius: theme.radius.pill, overflow: 'hidden', backgroundColor: theme.colors.surface.canvas }}><View style={{ width: `${Math.max(count ? count / maxStool * 100 : 7, 7)}%`, height: '100%', backgroundColor: theme.colors.entry.bowel.fg, borderRadius: theme.radius.pill }} /></View><AppText variant="caption" style={{ width: theme.controls.insightsChartCountWidth, fontSize: theme.typography.eyebrow.fontSize, textAlign: 'right' }}>{count}</AppText></View>)}</View><View style={{ flexDirection: 'row', alignItems: 'center', gap: theme.spacing.xs }}><Info size={theme.controls.smallIcon - 1} color={theme.colors.text.secondary} /><AppText variant="caption" tone="secondary" style={{ fontSize: theme.typography.eyebrow.fontSize }}>{t('tapHint')}</AppText></View></ChartCard>
        <ChartCard title={t('symptomsTitle')} eyebrow={t('symptomsEyebrow', { defaultValue: 'SYMPTOMS' })} period={t('period', { range })} desktop={desktop}><View style={{ height: theme.controls.insightsChartHeight, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-around', borderBottomWidth: theme.controls.borderWidth, borderColor: theme.colors.border.default, paddingTop: theme.controls.insightsChartGap }}>{[0, 1, 2, 3, 4, 5, 6].map((day) => <View key={day} style={{ flex: 1, height: '100%', alignItems: 'center', justifyContent: 'flex-end', gap: theme.controls.insightsChartDayGap }}><View style={{ height: theme.controls.insightsChartBarHeight, justifyContent: 'flex-end', flexDirection: 'row', alignItems: 'flex-end', gap: theme.spacing.xs - 1 }}><View style={{ width: theme.controls.insightsChartBarWidth, height: Math.max(7, Math.min(100, bloating * 34 + 7)), backgroundColor: theme.colors.feedback.danger.fg, borderRadius: theme.controls.insightsChartBarRadius }} /><View style={{ width: theme.controls.insightsChartBarWidth, height: Math.max(7, Math.min(100, pain * 34 + 7)), backgroundColor: theme.colors.feedback.warning.fg, borderRadius: theme.controls.insightsChartBarRadius }} /></View><AppText variant="caption" tone="secondary" style={{ fontSize: theme.typography.eyebrow.fontSize }}>{t(`week.${day}`)}</AppText></View>)}</View><View style={{ flexDirection: 'row', gap: theme.spacing.md, marginTop: theme.controls.insightsChartGap }}><AppText variant="caption" tone="secondary" style={{ fontSize: theme.typography.eyebrow.fontSize, color: theme.colors.feedback.danger.fg }}>● {t('bloating')}</AppText><AppText variant="caption" tone="secondary" style={{ fontSize: theme.typography.eyebrow.fontSize, color: theme.colors.feedback.warning.fg }}>● {t('pain')}</AppText></View></ChartCard>
      </View>
      <Card style={{ backgroundColor: theme.colors.feedback.success.bg, borderColor: theme.colors.feedback.success.bg, marginTop: 0 }}><View style={{ flexDirection: 'row', gap: theme.spacing.md }}><View style={{ width: theme.controls.quickLogIconSize + theme.spacing.xs, height: theme.controls.quickLogIconSize + theme.spacing.xs, borderRadius: theme.radius.md, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.colors.surface.card }}><Sparkles size={theme.controls.quickLogIconGlyph + theme.spacing.xs * 2} color={theme.colors.feedback.success.fg} /></View><View style={{ flex: 1, gap: theme.spacing.xs }}><AppText variant="caption" style={{ color: theme.colors.feedback.success.fg, fontSize: theme.typography.eyebrow.fontSize, fontWeight: '700', letterSpacing: theme.spacing.xs / 4 }}>{t('patternEyebrow').toUpperCase()}</AppText><AppText variant="sectionTitle">{t('patternTitle')}</AppText><AppText variant="body" tone="secondary" style={{ fontSize: theme.typography.caption.fontSize - 1, lineHeight: theme.typography.caption.lineHeight }}>{rangeRecords.length ? t('patternBody', { count: bloating }) : t('noData')}</AppText><View style={{ flexDirection: 'row', gap: theme.spacing.lg, paddingTop: theme.spacing.sm, borderTopWidth: theme.controls.borderWidth, borderColor: theme.colors.border.default }}><View><AppText variant="sectionTitle">{rangeRecords.filter((record) => record.kind === 'food').length}</AppText><AppText variant="caption" tone="secondary" style={{ fontSize: theme.typography.eyebrow.fontSize }}>{t('meals')}</AppText></View><View><AppText variant="sectionTitle">{bloating}</AppText><AppText variant="caption" tone="secondary" style={{ fontSize: theme.typography.eyebrow.fontSize }}>{t('bloating')}</AppText></View></View><View style={{ flexDirection: 'row', alignItems: 'center', gap: theme.spacing.md, paddingTop: theme.spacing.sm }}><Pressable onPress={() => setExpanded((value) => !value)} style={{ flexDirection: 'row', alignItems: 'center', gap: theme.spacing.xs - 1 }}><AppText variant="label">{expanded ? t('collapse') : t('why')}</AppText><ChevronDown size={theme.controls.smallIcon - 1} color={theme.colors.text.primary} /></Pressable>{expanded && <Button label={t('related')} onPress={() => setRelatedOpen(true)} />}</View>{expanded && <AppText variant="caption" tone="secondary" style={{ fontSize: theme.typography.caption.fontSize - 3 }}>{t('disclaimer')}</AppText>}</View></View></Card>
      <Card><View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><View><AppText variant="caption" style={{ fontSize: theme.typography.eyebrow.fontSize, fontWeight: '700', letterSpacing: theme.spacing.xs / 4 }}>{t('consistency').toUpperCase()}</AppText><AppText variant="sectionTitle" style={{ marginTop: theme.spacing.xs }}>{t('consistency')}</AppText><AppText variant="caption" tone="secondary">{loggedDays} {t('activeDays')} · {active}%</AppText></View><AppText variant="heroTitle">{active}%</AppText></View></Card><Button variant="secondary" label={t('report')} icon={FileText} onPress={() => router.push('/report')} />
      <Sheet visible={relatedOpen} title={t('related')} onClose={() => setRelatedOpen(false)}>{related.length ? related.map((record) => <Card key={record.id}><AppText variant="label">{recordTitle(record)}</AppText><AppText variant="caption" tone="secondary">{displayDate(record.localDate, i18n.language)} · {recordSummary(record)}</AppText></Card>) : <AppText tone="secondary">{t('noRelated')}</AppText>}</Sheet>
    </View>
  </Screen>;
}

function ChartCard({ title, eyebrow, period, children, desktop }: { title: string; eyebrow: string; period: string; children: ReactNode; desktop: boolean }) { const theme = useTheme(); return <Card style={{ flex: desktop ? 1 : undefined, minHeight: theme.controls.insightsCardMinHeight, padding: theme.spacing.lg }}><View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }}><View style={{ gap: theme.spacing.xs }}><AppText variant="caption" style={{ fontSize: theme.typography.eyebrow.fontSize, fontWeight: '700', letterSpacing: theme.spacing.xs * 0.3 }}>{eyebrow}</AppText><AppText variant="sectionTitle" style={{ fontWeight: '400' }}>{title}</AppText></View><AppText variant="caption" tone="secondary" style={{ fontSize: theme.typography.caption.fontSize - 3 }}>{period}</AppText></View><View style={{ flex: 1, justifyContent: 'center' }}>{children}</View></Card>; }
