import { useMemo } from 'react';
import { Pressable, View, useWindowDimensions } from 'react-native';
import { ArrowLeft, Clock3, ShieldCheck } from 'lucide-react-native';
import { useRouter } from 'expo-router';
import { useTranslation } from 'react-i18next';
import { AppText, Button, Card, Screen, useTheme } from '@/design-system';
import { localDateKey } from '@/domain/records';
import { useAppStore } from '@/state/useAppStore';

const startDate = () => { const date = new Date(); date.setHours(12, 0, 0, 0); date.setDate(date.getDate() - 13); return localDateKey(date); };

export function ReportScreen() {
  const theme = useTheme(); const { width } = useWindowDimensions(); const desktop = width > 820; const router = useRouter(); const { t } = useTranslation(['report', 'common']); const records = useAppStore((state) => state.records); const entries = useMemo(() => records.filter((record) => record.localDate >= startDate()), [records]);
  const bowel = entries.filter((record) => record.kind === 'bowel'); const symptoms = entries.filter((record) => record.kind === 'symptom'); const food = entries.filter((record) => record.kind === 'food'); const dairy = food.filter((record) => record.details.items.some((item) => item.name.toLowerCase().includes('milk') || item.name.includes('奶'))); const activeDays = new Set(entries.map((record) => record.localDate)).size; const stool = [1, 2, 3, 4, 5, 6, 7].map((type) => bowel.filter((record) => record.details.stoolType === type).length); const zoneTotal = Math.max(1, bowel.length); const zones = [stool[0] + stool[1], stool[2] + stool[3], stool[4] + stool[5] + stool[6]]; const top = stool.reduce((best, count, index) => count > best.count ? { index, count } : best, { index: 0, count: 0 });
  return <Screen topbar>
    <View style={{ marginTop: theme.spacing.md, gap: theme.spacing.md }}>
      <View style={{ flexDirection: desktop ? 'row' : 'column', alignItems: desktop ? 'flex-end' : 'flex-start', justifyContent: 'space-between', gap: theme.spacing.md }}><View style={{ gap: theme.spacing.sm, width: '100%' }}><AppText variant="eyebrow" tone="secondary">{t('eyebrow')}</AppText><AppText variant="webPageTitle" style={{ fontWeight: '700', fontSize: desktop ? undefined : 38, lineHeight: desktop ? undefined : 42 }} accessibilityRole="header">{t('title')}</AppText></View><Button variant="secondary" label={t('backToInsights')} icon={ArrowLeft} onPress={() => router.back()} /></View>
      <View style={{ minHeight: 152, flexDirection: 'row', alignItems: 'center', gap: theme.spacing.md, padding: theme.spacing.lg, marginTop: theme.spacing.md, borderRadius: theme.radius.lg, backgroundColor: theme.colors.action.primary.background }}><View style={{ flex: 1, minWidth: 0, gap: theme.spacing.xs }}><AppText variant="eyebrow" style={{ color: theme.colors.action.primary.foreground }}>{t('coverageLabel')}</AppText><AppText variant="heroTitle" style={{ color: theme.colors.action.primary.foreground, fontWeight: '700' }}>{activeDays}<AppText variant="sectionTitle" style={{ color: theme.colors.action.primary.foreground, letterSpacing: 0 }}> {t('ofDays')}</AppText></AppText><AppText variant="caption" style={{ color: theme.colors.action.primary.foreground, opacity: 0.75 }}>{entries.length ? t('reviewed', { count: entries.length }) : t('empty')}</AppText></View><View style={{ flexShrink: 0, width: 64, height: 64, borderRadius: theme.radius.pill, borderWidth: 1, borderColor: theme.colors.action.primary.foreground, alignItems: 'center', justifyContent: 'center' }}><AppText variant="sectionTitle" style={{ color: theme.colors.action.primary.foreground, fontSize: 18 }}>{Math.round(activeDays / 14 * 100)}%</AppText><AppText variant="caption" style={{ color: theme.colors.action.primary.foreground, opacity: 0.75, fontSize: 9, marginTop: -4 }}>{t('coveragePercent')}</AppText></View></View>
      <View style={{ flexDirection: desktop ? 'row' : 'row', flexWrap: desktop ? 'nowrap' : 'wrap', gap: theme.spacing.sm }}>{[[t('bowel'), bowel.length, t('times')], [t('symptoms'), symptoms.length, t('entry')], [t('food'), food.length, t('meal')], [t('dairy'), dairy.length, t('meal')]].map(([label, value, suffix]) => <Card key={String(label)} style={{ flex: desktop ? 1 : undefined, width: desktop ? undefined : '48%', minHeight: 74, padding: theme.spacing.md, flexDirection: 'row', alignItems: 'baseline', gap: theme.spacing.xs }}><AppText variant="caption" tone="secondary" style={{ fontSize: 10 }}>{label}</AppText><AppText variant="sectionTitle" style={{ fontSize: 25 }}>{value}</AppText><AppText variant="caption" tone="secondary" style={{ fontSize: 10 }}>{suffix}</AppText></Card>)}</View>
      <Card style={{ padding: theme.spacing.lg }}><View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: theme.spacing.sm }}><View style={{ flex: 1, minWidth: 0, gap: 4 }}><AppText variant="caption" style={{ fontSize: 10, fontWeight: '700', letterSpacing: 1.2 }}>{t('stool').toUpperCase()}</AppText><AppText variant="sectionTitle" style={{ fontWeight: '400' }}>{t('stoolTitle')}</AppText></View><AppText variant="caption" tone="secondary" style={{ fontSize: 11, flexShrink: 1, textAlign: 'right' }}>{t('periodLegend')}</AppText></View><View style={{ gap: 15, marginVertical: theme.spacing.lg }}>{zones.map((value, index) => { const labels = [t('hard'), t('ideal'), t('loose')]; const tone = [theme.colors.entry.bowel.fg, theme.colors.feedback.success.fg, theme.colors.feedback.danger.fg][index]; return <View key={labels[index]} style={{ flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm }}><AppText variant="caption" tone="secondary" style={{ width: 132, fontSize: 11 }}>{labels[index]}</AppText><View style={{ flex: 1, height: 8, borderRadius: theme.radius.pill, overflow: 'hidden', backgroundColor: theme.colors.surface.canvas }}><View style={{ width: `${Math.max(value / zoneTotal * 100, 0.5)}%`, height: '100%', backgroundColor: tone, borderRadius: theme.radius.pill }} /></View><AppText variant="label" style={{ width: 20, fontSize: 11, textAlign: 'right' }}>{value}</AppText></View>; })}</View><View style={{ flexDirection: 'row', gap: theme.spacing.xs, paddingTop: theme.spacing.md, borderTopWidth: 1, borderColor: theme.colors.border.default }}>{stool.map((value, index) => <View key={index} style={{ flex: 1, paddingVertical: theme.spacing.sm, alignItems: 'center', gap: theme.spacing.xs, backgroundColor: theme.colors.surface.canvas, borderRadius: theme.radius.sm }}><AppText variant="caption" tone="secondary" style={{ fontSize: 9 }}>{t('typeLabel', { type: index + 1 })}</AppText><AppText variant="label">{value}</AppText></View>)}</View><AppText variant="caption" tone="secondary" style={{ marginTop: theme.spacing.md, fontSize: 11 }}>{t('most', { type: top.index + 1, count: top.count })}</AppText></Card>
      <Card style={{ padding: theme.spacing.lg }}><View style={{ gap: 4 }}><AppText variant="caption" style={{ fontSize: 10, fontWeight: '700', letterSpacing: 1.2 }}>{t('stoodOut')}</AppText><AppText variant="sectionTitle">{t('focusTitle')}</AppText></View><AppText variant="body" style={{ marginTop: theme.spacing.sm, fontSize: 15, lineHeight: 24 }}>{bowel.length ? t('summary') : t('notEnough')}</AppText>{activeDays < 7 ? <View style={{ marginTop: theme.spacing.md, padding: theme.spacing.md, flexDirection: 'row', gap: theme.spacing.sm, backgroundColor: theme.colors.surface.canvas, borderRadius: theme.radius.md }}><Clock3 size={17} color={theme.colors.text.secondary} /><AppText variant="caption" tone="secondary">{t('clearerPicture')}</AppText></View> : <View style={{ marginTop: theme.spacing.md, borderTopWidth: 1, borderColor: theme.colors.border.default }}>{[[t('dairy'), dairy.length], [t('symptoms'), symptoms.length]].map(([label, value]) => <View key={String(label)} style={{ minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderColor: theme.colors.border.default }}><AppText variant="caption" tone="secondary">{label}</AppText><AppText variant="label">{value}</AppText></View>)}</View>}</Card>
      <Card style={{ flexDirection: 'row', gap: theme.spacing.sm, backgroundColor: theme.colors.surface.canvas }}><ShieldCheck size={18} color={theme.colors.feedback.success.fg} /><View style={{ flex: 1 }}><AppText variant="label">{t('disclaimerTitle')}</AppText><AppText variant="caption" tone="secondary" style={{ marginTop: theme.spacing.xs }}>{t('disclaimer')}</AppText></View></Card>
    </View>
  </Screen>;
}
